name: CI
on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TARGET_WORKSPACE: workflow_sync_target

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: makerling/workflow_sync_source
          path: workflow_sync_source

      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          path: ${{ env.TARGET_WORKSPACE }}

      - name: Sync directories
        run: |
          pip3 install dirsync
          python ${{ env.TARGET_WORKSPACE }}/sync.py
          
      - name: Update changes in GitHub repository
        run:  |
          cd ${{ env.TARGET_WORKSPACE }}
          git config --global user.name 'makerling' 
          git config --global user.email 'github@makerling.com'
          git add -A
          git commit -m '[automated commit] added synced files'
          git push